import '../models/product.dart';

class MockData {
  static const List<String> categories = [
    'All',
    'Women',
    'Men',
    'Dresses',
    'Tops',
    'Bottoms',
    'Outerwear',
    'Accessories',
  ];

  static final List<Product> products = [
    Product(
      id: '1',
      name: 'Silk Slip Dress',
      brand: 'Maison Elara',
      description:
          'Luxuriously smooth silk slip dress with delicate adjustable straps. '
          'Designed for effortless elegance, this piece transitions seamlessly from day to evening.',
      price: 189.00,
      originalPrice: 280.00,
      rating: 4.8,
      reviewCount: 124,
      images: [
        'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600',
        'https://images.unsplash.com/photo-1566206091558-7f218b696731?w=600',
        'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600',
      ],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['Ivory', 'Blush', 'Black'],
      category: 'Dresses',
      isFavorite: true,
      badge: 'SALE',
    ),
    Product(
      id: '2',
      name: 'Oversized Linen Blazer',
      brand: 'Studio Noire',
      description: 'A modern take on the classic blazer in breathable linen. '
          'Oversized silhouette with a relaxed drape, perfect for smart-casual looks.',
      price: 245.00,
      rating: 4.6,
      reviewCount: 89,
      images: [
        'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600',
        'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600',
      ],
      sizes: ['XS', 'S', 'M', 'L'],
      colors: ['Sand', 'White', 'Navy'],
      category: 'Outerwear',
      isNew: true,
    ),
    Product(
      id: '3',
      name: 'High-Rise Wide Leg Trousers',
      brand: 'Atelier Forme',
      description:
          'Tailored wide-leg trousers with a high-rise waist and clean front pleat. '
          'A wardrobe staple that elevates any outfit.',
      price: 165.00,
      originalPrice: 210.00,
      rating: 4.7,
      reviewCount: 201,
      images: [
        'https://images.unsplash.com/photo-1594938298603-c8148c4b4545?w=600',
        'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600',
      ],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['Camel', 'Black', 'Ecru'],
      category: 'Bottoms',
      badge: 'SALE',
    ),
    Product(
      id: '4',
      name: 'Ribbed Cashmere Turtleneck',
      brand: 'Maison Elara',
      description: 'Pure cashmere turtleneck with fine ribbing throughout. '
          'Exceptionally soft with a slim, refined silhouette.',
      price: 320.00,
      rating: 4.9,
      reviewCount: 67,
      images: [
        'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600',
        'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600',
      ],
      sizes: ['XS', 'S', 'M', 'L'],
      colors: ['Oatmeal', 'Charcoal', 'Forest'],
      category: 'Tops',
      isNew: true,
    ),
    Product(
      id: '5',
      name: 'Leather Mini Skirt',
      brand: 'Studio Noire',
      description:
          'Genuine lambskin leather mini skirt with a side zip closure. '
          'A bold piece that pairs effortlessly with knitwear or structured tops.',
      price: 295.00,
      rating: 4.5,
      reviewCount: 43,
      images: [
        'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600',
        'https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=600',
      ],
      sizes: ['XS', 'S', 'M', 'L'],
      colors: ['Black', 'Cognac'],
      category: 'Bottoms',
    ),
    Product(
      id: '6',
      name: 'Floral Midi Dress',
      brand: 'Atelier Forme',
      description:
          'Romantic floral print on fluid fabric with puff sleeves and a tiered skirt. '
          'A feminine, statement piece for any occasion.',
      price: 215.00,
      originalPrice: 260.00,
      rating: 4.7,
      reviewCount: 158,
      images: [
        'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600',
        'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600',
      ],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['Floral Blue', 'Floral Pink'],
      category: 'Dresses',
      badge: 'POPULAR',
    ),
    Product(
      id: '7',
      name: 'Structured Canvas Tote',
      brand: 'Maison Elara',
      description:
          'Heavy-gauge canvas tote with leather trim and interior pockets. '
          'Spacious enough for everyday essentials, refined enough for the office.',
      price: 145.00,
      rating: 4.8,
      reviewCount: 312,
      images: [
        'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600',
        'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600',
      ],
      sizes: ['One Size'],
      colors: ['Natural', 'Black', 'Olive'],
      category: 'Accessories',
      isNew: true,
    ),
    Product(
      id: '8',
      name: 'Tailored Wool Coat',
      brand: 'Studio Noire',
      description:
          'Double-breasted wool-blend coat with notched lapels and a belt. '
          'A timeless investment piece in a classic silhouette.',
      price: 580.00,
      originalPrice: 720.00,
      rating: 4.9,
      reviewCount: 54,
      images: [
        'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600',
        'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600',
      ],
      sizes: ['XS', 'S', 'M', 'L'],
      colors: ['Camel', 'Black', 'Grey'],
      category: 'Outerwear',
      badge: 'SALE',
    ),
    Product(
      id: '9',
      name: 'Classic White Shirt',
      brand: 'Maison Elara',
      description: 'Crisp cotton white shirt with a tailored fit.',
      price: 120.00,
      rating: 4.5,
      reviewCount: 88,
      images: [
        'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600',
      ],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['White'],
      category: 'Tops',
    ),
    Product(
      id: '10',
      name: 'Denim Jacket',
      brand: 'Studio Noire',
      description: 'Classic blue denim jacket with a modern cut.',
      price: 210.00,
      rating: 4.6,
      reviewCount: 132,
      images: [
        'https://images.unsplash.com/photo-1544441893-675973e31985?w=600',
      ],
      sizes: ['S', 'M', 'L'],
      colors: ['Blue'],
      category: 'Outerwear',
    ),
    Product(
      id: '11',
      name: 'Pleated Midi Skirt',
      brand: 'Atelier Forme',
      description: 'Elegant pleated skirt with flowy silhouette.',
      price: 175.00,
      rating: 4.7,
      reviewCount: 95,
      images: [
        'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600',
      ],
      sizes: ['XS', 'S', 'M', 'L'],
      colors: ['Beige', 'Black'],
      category: 'Bottoms',
    ),
    Product(
      id: '12',
      name: 'Knitted Sweater',
      brand: 'Maison Elara',
      description: 'Warm knitted sweater perfect for winters.',
      price: 190.00,
      rating: 4.8,
      reviewCount: 76,
      images: [
        'https://images.unsplash.com/photo-1516826957135-700dedea698c?w=600',
      ],
      sizes: ['S', 'M', 'L'],
      colors: ['Grey', 'Cream'],
      category: 'Tops',
      isNew: true,
    ),
    Product(
      id: '13',
      name: 'Slim Fit Jeans',
      brand: 'Studio Noire',
      description: 'Stretchable slim fit jeans for everyday wear.',
      price: 160.00,
      rating: 4.4,
      reviewCount: 140,
      images: [
        'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600',
      ],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Blue', 'Black'],
      category: 'Bottoms',
    ),
    Product(
      id: '14',
      name: 'Summer Maxi Dress',
      brand: 'Atelier Forme',
      description: 'Lightweight maxi dress for summer outings.',
      price: 220.00,
      rating: 4.7,
      reviewCount: 110,
      images: [
        'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600',
      ],
      sizes: ['S', 'M', 'L'],
      colors: ['Yellow', 'White'],
      category: 'Dresses',
    ),
    Product(
      id: '15',
      name: 'Leather Handbag',
      brand: 'Maison Elara',
      description: 'Premium leather handbag with elegant design.',
      price: 350.00,
      rating: 4.9,
      reviewCount: 60,
      images: [
        'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600',
      ],
      sizes: ['One Size'],
      colors: ['Black', 'Brown'],
      category: 'Accessories',
      badge: 'POPULAR',
    ),
    Product(
      id: '16',
      name: 'Casual Hoodie',
      brand: 'Studio Noire',
      description: 'Comfortable hoodie for daily wear.',
      price: 130.00,
      rating: 4.6,
      reviewCount: 150,
      images: [
        'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600',
      ],
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Grey', 'Black'],
      category: 'Tops',
    ),
    Product(
      id: '17',
      name: 'Formal Blazer',
      brand: 'Atelier Forme',
      description: 'Sharp formal blazer for office wear.',
      price: 280.00,
      rating: 4.8,
      reviewCount: 70,
      images: [
        'https://images.unsplash.com/photo-1593032465175-481ac7f401a0?w=600',
      ],
      sizes: ['S', 'M', 'L'],
      colors: ['Black', 'Navy'],
      category: 'Outerwear',
    ),
    Product(
      id: '18',
      name: 'Sports Sneakers',
      brand: 'Maison Elara',
      description: 'Lightweight sneakers for running and casual wear.',
      price: 200.00,
      rating: 4.7,
      reviewCount: 180,
      images: [
        'https://images.unsplash.com/photo-1528701800489-20be3c1c7c66?w=600',
      ],
      sizes: ['7', '8', '9', '10'],
      colors: ['White', 'Black'],
      category: 'Accessories',
    ),
  ];

  static final List<Order> orders = [
    Order(
      id: 'ORD-4821',
      date: DateTime.now().subtract(const Duration(days: 3)),
      status: 'Shipped',
      total: 354.00,
      items: [
        CartItem(product: products[0], size: 'S', color: 'Ivory', quantity: 1),
        CartItem(
            product: products[6],
            size: 'One Size',
            color: 'Natural',
            quantity: 1),
      ],
    ),
    Order(
      id: 'ORD-3917',
      date: DateTime.now().subtract(const Duration(days: 14)),
      status: 'Delivered',
      total: 165.00,
      items: [
        CartItem(product: products[2], size: 'M', color: 'Camel', quantity: 1),
      ],
    ),
    Order(
      id: 'ORD-3304',
      date: DateTime.now().subtract(const Duration(days: 30)),
      status: 'Delivered',
      total: 640.00,
      items: [
        CartItem(product: products[1], size: 'S', color: 'Sand', quantity: 1),
        CartItem(
            product: products[3], size: 'S', color: 'Oatmeal', quantity: 1),
      ],
    ),
  ];
}
